apiVersion: v1
kind: Service
metadata:
  name: iris-model-v${MODEL_VERSION}-service
spec:
  type: LoadBalancer
  selector:
    app: iris-model
    version: v${MODEL_VERSION}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8200
